### ISSUE TITLE
broken with jellybeans

### ISSUE THREAD

**Issue by kevinlawler** [qualiabyte/vim-colorstepper#5]
emits list of errors and does not switch when cycling through

https://github.com/nanotech/jellybeans.vim

https://github.com/nanotech/jellybeans.vim/issues/84

**Comment by qualiabyte** [comment]
Hi @kevinlawler, thanks for reporting this issue.
While I'm not using Vim at the moment, luckily @JaSpa offered a solution which I've merged.
Hopefully it will solve the problem, let us know how it works for you!
